typography_spectrum: 0.46650307020172477
color:
  brandStrength: 0.09585746773518622
  lightness: 0.40684598474763334
  saturation: 0.4433920334558934
  rhythmicContrast: 0.4317009346559644
  brandColors:
    - '#F4FCFE'
    - '#669791'
    - '#CB9163'
    - '#4B2637'
    - '#0A0000'
opengraph:
  appId: '1214958998562838'
layout_spectrum: 0.910627351840958
analytics:
  google: UA-51092082-18
  facebook: '174617379709706'
author:
  name: David Strom
  email: dstorm@peakwinathletics.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/caf7a987-3a92-4ee6-88d7-1828b42e5324.png
name: draglabs
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/979b55dc-8c8c-43a5-ba12-5c5e31a1c0db.png
title: Drag Labs
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FUtwPhd7gSss%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUtwPhd7gSss&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FUtwPhd7gSss%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Buteaupia Productions
          url: 'https://www.youtube.com/channel/UCOvC_QCu0i3NX1im29uIFuQ'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: >-
        What is DragLabs, DragLabs is a music platform dedicated to cultivating
        regional sound.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=UtwPhd7gSss'
      title: What is Drag Labs?
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Some day music will save us... savor the day. '
purpose:
  - type: contact
    url: 'mailto:dstorm@peakwinathletics.com'
    label: Contact us
github: true
