typography_spectrum: 0.46650307020172477
color:
  brandStrength: 0.09585746773518622
  lightness: 0.40684598474763334
  saturation: 0.4433920334558934
  rhythmicContrast: 0.4317009346559644
  brandColors:
    - '#F4FCFE'
    - '#669791'
    - '#CB9163'
    - '#4B2637'
    - '#0A0000'
opengraph:
  appId: '1214958998562838'
layout_spectrum: 0.910627351840958
analytics:
  google: UA-51092082-18
  facebook: '174617379709706'
author:
  name: David Strom
  email: dstorm@peakwinathletics.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/caf7a987-3a92-4ee6-88d7-1828b42e5324.png
name: draglabs
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/979b55dc-8c8c-43a5-ba12-5c5e31a1c0db.png
title: Drag Labs
content: []
description: 'Some day music will save us... savor the day. '
purpose:
  - type: contact
    url: 'mailto:dstorm@peakwinathletics.com'
    label: Contact us
github: true
